### ISSUE TITLE
Wrong install command for templates in templates GitHub repo

### ISSUE THREAD

**Issue by marcfilleul** [thedevdojo/static#5]
Hi,

I just noticed that the template install command is good in the Templates page or in the templates preview topbar but wrong at the bottom of the templates GitHub repo:

`static new folder-name --template=stone`

I guess it was the initial command that have been simplified but not corrected in the templates repo ;)

**Comment by tnylea** [comment]
Good catch 👏

Yep, that's exactly right. I've just updated all of the tempate repo Readme information.

Thanks a ton!
