### ISSUE TITLE
Page transitions guide?

### ISSUE THREAD

**Issue by ArnavK-09** [thedevdojo/static#7]

**Comment by tnylea** [comment]
Hey @ArnavK-09,

You can incorporate a number of libraries to accomplish page transitions; however, you can take a look at how we are doing thing with the Static website (https://static.devdojo.com). You can find that repo here: https://github.com/thedevdojo/static.devdojo.com

We are using HTMX to fetch pages, here's an example from this file: https://github.com/thedevdojo/static.devdojo.com/blob/main/includes/docs-sidebar.html

```
<button id="introduction-docs" hx-get="/docs/getting-started" hx-target="#docs-content" hx-select="#docs-content" hx-swap="outerHTML" hx-push-url="true" @click="scrollTop(); route=$el.getAttribute('hx-get'); leftSidebar=false;" ...>
    ...
</button>
```

You can see that when the button is clicked, it will scroll to the top of the page and load the new content.

You may also benefit from trying the new Google Transitions API. Here's a quick video where I explained how they work https://twitter.com/tnylea/status/1661846376005632003. Once these are fully supported you'll be able to build the links as normal `<a>` tags and then leverage the browser built-in page transitions.

Hope that helps. Let me know if you have any other specific questions.

Talk to you later 🍻
